<a href="https://colab.research.google.com/github/martian099/BambulabGcode/blob/main/240729_Pytorch_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
tensor = torch.rand(2, 3)
print(tensor)

tensor([[0.0462, 0.2021, 0.3641],
        [0.6129, 0.7862, 0.0183]])


In [4]:
list_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(list_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
result = tensor + list_tensor
print(result)

tensor([[1.0462, 2.2021, 3.3641],
        [4.6129, 5.7862, 6.0183]])
